services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    restart: always
    container_name: elasticsearch-test
    ports:
      - "8200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          #cpus: "4"
          memory: "1g" #1024M
    #mem_limit: ${ES_MEM_LIMIT}
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:${ELASTIC_PASSWORD} http://elasticsearch:9200 | grep 'cluster_name'"]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    container_name: kibana-test
    image: docker.elastic.co/kibana/kibana:8.17.0
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "6601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

  serilogtest:
    restart: always
    image: ${DOCKER_REGISTRY-}serilogtest:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: SerilogESTest/Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  elasticsearch-data:
